server:
  port: 8080
  servlet:
    context-path: /api/msf-chn-adminservice/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: America/Guayaquil

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-on-validation-error: false
    placeholders:
      schema_name: dbpruebagenerador
    validate-on-migrate: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

rsa:
  private-key: 245234234234==

token:
  access-expires-in-min: 5
  refresh-expires-in-min: 30

csrf:
  cookie:
    domain: localhost
    name: HKJHR64556