apiVersion: v1
kind: Pod
metadata:
  name: msf-chn-admin
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
spec:
  containers:
    - name: msf-chn-admin
      image: jmenadocker/msf-chn-admin:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://simplest-collector:4317"
      securityContext:
        allowPrivilegeEscalation: false # No hay escalada de privilegios dentro del contenedor
        runAsNonRoot: true             # El contenedor no se ejecuta como root
        readOnlyRootFilesystem: true   # Restringe el sistema de archivos del contenedor a solo lectura
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "128Mi"
